version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest  # Escolha a versão desejada
    restart: always
    environment:
      ACCEPT_EULA: Y # Aceita o contrato de licença
      SA_PASSWORD: "56642202Egr!" # Defina uma senha forte para o usuário SA
      MSSQL_USER: root
      MSSQL_PASSWORD: SenhaForte3!
    ports:
      - "1433:1433" # Mapeia a porta 1433 do host para o container
    volumes:
      - ./data:/var/opt/mssql/data